### ISSUE TITLE
Can't access subobject VAR arrays

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/spin2cpp#88] opened 2020-08-03 14:10 UTC
Code like this
```spin
OBJ
myobj : "whatever"
PUB test
myobj.arr[0] := 1
```
leads to a syntax error. Normal VARiables work fine.

**Comment by totalspectrum** [comment] 2020-08-03 22:40
Thanks. Spin doesn't allow access to any variables in subobjects at all, so I suppose we could document this as a "feature". But it isn't working as intended, I'll try to figure it out.

**Comment by Wuerfel21** [comment] 2020-08-03 23:53
Subobject VAR access is not documented? I know I learned about it _somewhere_...

**Comment by totalspectrum** [comment] 2020-08-04 00:02
Access to VAR in a subobject is a fastspin extension. In regular Spin I'm pretty sure you're not allowed to access subobject VARs. At least, openspin certainly doesn't allow it. I'm not sure if Chip has changed this for Spin2.

**Comment by Wuerfel21** [comment] 2020-08-04 00:34
I knew it's an extension, I just thought it was already documented somewhere

**Comment by Wuerfel21** [comment] 2020-08-04 16:17
[Indeed, it is](https://github.com/totalspectrum/spin2cpp/blob/master/doc/spin.md#access-to-member-variables)

**Comment by totalspectrum** [comment] 2020-11-28 17:29
This should be fixed as of commit 95be3af0. Thanks for the bug report!

**Closed by totalspectrum** 2020-11-28 17:29 UTC
