### ISSUE TITLE
Running binary does not work on Propeller Chip - 40-Pin DIP Chip

### ISSUE THREAD

**Issue by jonpchin** [totalspectrum/spin2cpp#25] opened 2017-12-16 17:26 UTC
I tested a blink.spin which blinks LED and uploaded it to the Propeller 40 pin DIP chip using the Prop USB plug and it blinks the LED just fine. But running the .binary file does not seem to work after I transform the file blink.spin to blink.binary. The upload is fine but nothing happens once the blink.binary is uploaded. Does the Propeller Chip 40 pin DIP not support Propeller C? I originally tried getting this to work in SimpleIDE using C code and it had the same problem so it led me down to this path.

**Comment by jonpchin** [comment] 2017-12-16 17:30
The blink.spin file I used to test on the Propeller 40 pin DIP chip:

CON
  Delay = 9_000_000  

  MY_LED_PIN = 26 ' Use pin 26

PUB main
  DIRA[MY_LED_PIN] := 1 ' Set the LED pin to an output

  repeat ' Repeat forever
    OUTA[MY_LED_PIN] := 1  ' Turn the LED on
    waitcnt(cnt + Delay) ' Wait 1 second
                           ' cnt is the clock tick counter,
                           ' clkfreq is the number of clock ticks in a second
    OUTA[MY_LED_PIN] := 0  ' Turn the LED off
    waitcnt(cnt + Delay) ' Wait 1 second

**Comment by totalspectrum** [comment] 2018-01-02 00:42
Generally speaking all of the Propeller chips support Propeller C, so I don't think your problem is in the chip. Most likely you're hitting some kind of compiler bug. I have seen issues sometimes with the compiler optimizing away references to the CNT register, which can lead to strange bugs sometimes. Have you tried compiling with optimization disabled? That might help.

Another thing you could try is using spin2cpp's asm mode to directly compile the code:

spin2cpp --asm --binary --code=hub --data=hub blink.spin

should produce a blink.binary directly, without using Propeller C at all.

**Comment by jonpchin** [comment] 2018-01-02 05:27
I tried your suggestion spin2cpp --asm --binary --code=hub --data=hub blink.spin and the result is still the same.

**Comment by jonpchin** [comment] 2018-01-02 05:32
How do I disable optimizations when compling?

**Comment by drawkula** [comment] 2018-03-17 10:52
I reduced the delay to have a faster blinking and ran the output of `spin2cpp --asm --binary --code=hub --data=hub blink.spin` in GEAR (because I had no simple Propeller board with a LED at hand) and it did blink in the Propeller simulator.

**Comment by jonpchin** [comment] 2018-03-17 17:01
What did you reduce the delay too? I tried the three following delays and still the same result:
Delay = 9_000_000
Delay = 3_000_000    
Delay = 1_000_000  

I am not using GEAR but I am using the 40 pin DIP chip P8X32A-D40  with the prop plug for uploading the code.

**Comment by jonpchin** [comment] 2018-03-17 17:05
I am using P8X32A-Propellent-v1.6 to upload the blink.binary file.

**Comment by drawkula** [comment] 2018-03-17 17:15
Gear is a Propeller simulation.

—▶ https://github.com/davispuh/gear-emu/releases/tag/V14.07.03

I reduced the delay to 100_000 because the simulation is slower than the original Propeller, but that should not have an impact on the correctness of your code.

I cannot test Propellent because I'm using Debian (v9.4.0/AMD64).

**Comment by jonpchin** [comment] 2018-03-17 18:57
I tried testing on Linux with Propller IDE which uses spin language and the blink works fine. But when I try the SimpleIDE using C on Linux it does not work. This was the original issue I saw in Windows as well when running SimpleIDE. 

I think the C code in SimpleIDE is getting converted to .binary and that is uploaded to the chip. I guess I'll just code in spin for now.

**Comment by jonpchin** [comment] 2018-03-17 18:59
The console log of SimpleIDE says it loaded into RAM successfully but the LED does not blink.

**Comment by drawkula** [comment] 2018-03-17 19:12
And the C code is?

**Comment by jonpchin** [comment] 2018-03-17 20:40
/*
  Blink Light.c
 
  Blink light circuit connected to P26.
*/

#include "simpletools.h"                      // Include simpletools

int main()                                    // main function
{
  while(1)                                    // Endless loop
  {
    high(26);                                 // Set P26 I/O pin high
    pause(1000);                               // Wait 1 second
    low(26);                                  // Set P26 I/O pin low
    pause(1000);                               // Wait another 1 second
  }
}

**Comment by drawkula** [comment] 2018-03-18 07:49
Oh sorry...
I have no idea how to use and link to those "Simple Libraries".
They are far too complicated for me! ;-)

I use "naked C", an editor of my liking and shell tools instead of SimpleIDE and its libraries. That way names of registers and functions are very similar to Spin and PASM.
```
#include "propeller.h"

int main(int argc, char* argv[])
{
    int pin  = 26;
    int freq = CLKFREQ>>1; // half of the ticks of a full period

    DIRA |= (1<<pin);

    for(;;) {
        OUTA |= (1<<pin);;
        waitcnt(freq+getcnt());
        OUTA &= ~(1<<pin);
        waitcnt(freq+getcnt());
    }
}
```
This "blinks" in the simulator.

My (self built) PropGCC is...
```
$ /opt/parallax/bin/propeller-elf-gcc -v
Using built-in specs.
COLLECT_GCC=/opt/parallax/bin/propeller-elf-gcc
COLLECT_LTO_WRAPPER=/opt/parallax/libexec/gcc/propeller-elf/4.6.1/lto-wrapper
Target: propeller-elf
Configured with: /opt/parallax.src/propgcc/gcc/configure --target=propeller-elf --prefix=/opt/parallax --disable-nls --disable-shared --with-pkgversion=propellergcc-alpha_v1_9_0_propellergcc-alpha_v1_9_1-5-g5fc1abdab --with-bugurl=http://code.google.com/p/propgcc/issues
Thread model: single
gcc version 4.6.1 (propellergcc-alpha_v1_9_0_propellergcc-alpha_v1_9_1-5-g5fc1abdab) 
```
My "naked C" code working in my context cannot exclude bugs in SimpleTools or your PropGCC.

Pleaaaaase... someone with knowledge of SimpleTools jump in here...

**Comment by jonpchin** [comment] 2018-03-18 20:08
When I try to compile with prop gcc from simpleIDE I get.

blink.cpp: In function 'int main(int, char**)':
blink.cpp:12:9: error: 'getcnt' was not declared in this scope

I also tried building propgcc from source but ran into some problems building it.

**Comment by jonpchin** [comment] 2018-03-18 20:12
The propGCC from SimpleIDE is:

D:\Programs\spin2cpp>propeller-elf-gcc -v
Using built-in specs.
COLLECT_GCC=propeller-elf-gcc
COLLECT_LTO_WRAPPER=c:/program files (x86)/simpleide/propeller-gcc/bin/../libexec/gcc/propeller-elf/4.6.1/lto-wrapper.exe
Target: propeller-elf
Configured with: ../../propgcc/gcc/configure --target=propeller-elf --prefix=/opt/parallax --disable-nls --disable-libssp --disable-lto --disable-shared --with-pkgversion=propellergcc_v1_0_0_2408 --with-bugurl=http://code.google.com/p/propgcc/issues
Thread model: single
gcc version 4.6.1 (propellergcc_v1_0_0_2408)

**Comment by drawkula** [comment] 2018-03-18 20:17
You're compiling it as C++ code.

**Comment by jonpchin** [comment] 2018-03-19 04:14
D:\Programs\spin2cpp>propeller-elf-gcc blink.c
C:\Users\jonc\AppData\Local\Temp\ccP3pDVm.o: In function `_main':
(.text+0xb4): undefined reference to `_getcnt'
C:\Users\jonc\AppData\Local\Temp\ccP3pDVm.o: In function `_main':
(.text+0x104): undefined reference to `_getcnt'
collect2: ld returned 1 exit status

**Comment by jonpchin** [comment] 2018-03-19 04:31
If I do:
propeller-elf-gcc -c  blink.c
then there is no errors and it produces a blink.o, but how do I make it a blink.binary? I tried renaming the file and uploading that using Propellent.exe but it gives an error popup saying the file is corrupt or is not a Propeller application Word 3 (codebase) must be $0010

**Comment by drawkula** [comment] 2018-03-19 05:52
That `.o` file is only "blink.c" compiled, but not linked to the needed libc.
```
$ propeller-elf-gcc blink.c -o blink.elf
```
You can send that to the Propeller using `propeller-load`.
(I never did this with Windows, so use the name of the serial instead of $COMX.)
```
$ propeller-load -p $COMX -r blink.elf 
```
Your Propeller runs at 80MHz?
If not, add `-Dclkfreq=` and the right speed.

**Comment by totalspectrum** [comment] 2018-03-21 18:45
My guess is that it's a clock issue. I notice that your Spin code does not declare the clock frequency or mode. spin2cpp assumes an 80 MHz external crystal, as does Propeller GCC (most Parallax boards have this). If you're using a DIP chip in your project you may well not have an external crystal? In which case something (like the SimpleIDE pause() function) probably will not work properly.

drawkula's blink.c above should work. You can replace getcnt() with just CNT (on Prop1 they are identical, the getcnt() macro was introduced to make porting to Prop2 easier).

**Comment by totalspectrum** [comment] 2018-04-20 13:43
Closing for now as a "cannot reproduce". But if any more details come to light please re-open.

**Closed by totalspectrum** 2018-04-20 13:43 UTC
