### ISSUE TITLE
Global var gets cleared when built using the pasm backend (-O1 or higher)

### ISSUE THREAD

**Issue by avsa242** [totalspectrum/spin2cpp#372] opened 2023-04-23 18:20 UTC
Hey guys,

I'm trying to figure out how to get a PDM mic working with the P1 and when I try to build the code below with the pasm backend, the var `_smp` seems like gets cleared before being written to the hub.

I've tried to distill this down, but I'm not sure how easily it can be reproduced if you don't have a PDM mic (I'm using one of these: https://www.adafruit.com/product/3492).
Hopefully the pasm output will be obvious enough.

The code:

```spin
con

    _clkmode    = xtal1 + pll16x
    _xinfreq    = 5_000_000

    SRATE = 16000

var

    long _smp

obj

    ser: "FullDuplexSerial"

PUB main() | per, s, d, smp

    ser.start(31, 30, 0, 115200)
    waitcnt(cnt+clkfreq/10)

    per := clkfreq/SRATE

    { PDM CLK (out) }
    d := >|((1_024_000 - 1) / 1_000_000)
    s := (4 - d)
    ctra := (%00010 << 26) | (d << 23) | 0
    frqa := fraction(1_024_000, clkfreq, s)
    dira[0] := 1

    { PDM DATA (in) }
    ctrb := (%01010 << 26) | 1  'POSEDGE_DETECT | 1
    frqb := 1
    dira[1] := 0


    ser.bin(ctra, 32)
    newline()
    ser.bin(ctrb, 32)
    newline()
    ser.dec(per)
    newline()

    repeat
        phsb := 0
        waitcnt(cnt+per)
        _smp := phsb
        ser.dec(_smp)
        newline()

pri newline()

    ser.str(string(10, 13))

pri fraction(a, b, shift): f

    if (shift > 0)                              ' if shift, pre-shift a or b left
        a <<= shift                             ' to maintain significant bits while
    if (shift < 0)                              ' insuring proper result
        b <<= -shift

    repeat 32                                   ' perform long division of a/b
        f <<= 1
        if (a => b)
            a -= b
            f++
        a <<= 1

```

I think the `mov arg01, #0` on or about line 332 of the pasm output is what looks a little sus (it then looks like it `wrlong`'s it to the hub).

This builds fine at -O0 or with the bc backend. Adding the directive `{++opt(!regs)} ` to the `main()` definition also fixes it (so it's easy to work around), and from its description in the flexspin docs, it does sound apt.

Thanks in advance!

**Comment by Wuerfel21** [comment] 2023-04-23 19:47
The relevant asm:
```spin
_main
	mov	COUNT_, #1
	call	#pushregs_
	mov	arg01, #31
	mov	arg02, #30
	mov	arg03, #0
	mov	arg04, imm_115200_
	add	objptr, #4
	call	#LMM_CALL
	long	@@@_FullDuplexSerial_Start
	sub	objptr, #4
	rdlong	muldiva_, #0
	mov	muldivb_, #10
	call	#divide_
	mov	arg01, cnt
	add	arg01, muldivb_
	waitcnt	arg01, #0            ' <----- I THINK HE MEANS THIS MOV
	rdlong	muldiva_, #0
	mov	muldivb_, imm_16000_
	call	#divide_
	mov	local01, muldivb_
	mov	ctra, imm_142606336_
	rdlong	arg02, #0
	mov	arg01, imm_1024000_
	mov	arg03, #3
	call	#LMM_CALL
	long	@@@_fraction
	mov	frqa, result1
	or	dira, #1
	mov	ctrb, imm_671088641_
	mov	frqb, #1
	andn	dira, #2
	mov	arg01, ctra
	mov	arg02, #32
	add	objptr, #4
	call	#LMM_CALL
	long	@@@_FullDuplexSerial_Bin
	mov	arg01, ptr_L__0023_
	call	#LMM_CALL
	long	@@@_FullDuplexSerial_Str
	mov	arg01, ctrb
	mov	arg02, #32
	call	#LMM_CALL
	long	@@@_FullDuplexSerial_Bin
	mov	arg01, ptr_L__0023_
	call	#LMM_CALL
	long	@@@_FullDuplexSerial_Str
	mov	arg01, local01
	call	#LMM_CALL
	long	@@@_FullDuplexSerial_Dec
	mov	arg01, ptr_L__0023_
	call	#LMM_CALL
	long	@@@_FullDuplexSerial_Str
	sub	objptr, #4
LR__0001
	mov	phsb, #0
	mov	arg01, cnt
	add	arg01, local01
	waitcnt	arg01, #0
	wrlong	phsb, objptr
	mov	arg01, #0
	add	objptr, #4
	call	#LMM_CALL
	long	@@@_FullDuplexSerial_Dec
	mov	arg01, ptr_L__0023_
	call	#LMM_CALL
	long	@@@_FullDuplexSerial_Str
	sub	objptr, #4
	sub	__pc, #4*(($+1) - LR__0001)
	mov	sp, fp
	call	#popregs_
_main_ret
	call	#LMM_RET
```

**Comment by Wuerfel21** [comment] 2023-04-23 19:50
Oh, I see the issue. Ignore that MOV, it has nothing to do with anything.

The issue is that it moved PHSB into the left-side of a WRLONG, which only writes the shadow register.

**Comment by avsa242** [comment] 2023-04-23 19:52
Ohhh ok, misinterpreted ;)

**Comment by avsa242** [comment] 2023-04-23 19:56
hmm wierd...in my listing, that `wrlong` appears _after_ the `mov` (flexspin 6.1.1 final)
```spin
LR__0001
    mov phsb, #0
    mov arg01, cnt
    add arg01, local01
    waitcnt arg01, #0
    mov arg01, #0
    wrlong  arg01, objptr
    add objptr, #4
    call    #LMM_CALL
    long    @@@_FullDuplexSerial_Dec
    mov arg01, ptr_L__0023_
    call    #LMM_CALL
    long    @@@_FullDuplexSerial_Str
    sub objptr, #4
    sub __pc, #4*(($+1) - LR__0001)
    mov sp, fp
    call    #popregs_
_main_ret
    call    #LMM_RET
```

**Comment by Wuerfel21** [comment] 2023-04-23 19:56
Actually no, the MOV seems to be a separate bug

**Comment by Wuerfel21** [comment] 2023-04-23 19:59
Huh, I was using 6.1.1, too. But it looks like your output when I use a master build?

**Comment by Wuerfel21** [comment] 2023-04-23 20:00
Wait, no, it looks like yours when I use a master build where I modified the function to stop it from forwarding PHSB into the WRLONG.

**Comment by Wuerfel21** [comment] 2023-04-23 20:19
After much headache, fixed by above PR.

**Comment by avsa242** [comment] 2023-04-23 21:48
Confirmed, thanks! (and sorry for the headache)

**Closed** 2023-04-25 11:15 UTC
